services:
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: sail
      PMA_PASSWORD: password
    networks:
      - sail
    depends_on:
      - mysql

networks:
  sail:
    external: true
    name: to-do-list_fpw_sail